
/*
static void Main()
    {
        try{
            //int x=int.Parse("NotANumber");
            int a=20;
            int b=0;
            int recno=-22;
            if(recno<0){
                throw new RecordNotFoundException();
            }

            //int c=a/b;
            //Console.WriteLine(c);
        }
        catch(DivideByZeroException ex){
            Console.WriteLine($"Error: {ex.Message}");
        }
        catch(FormatException ex){
            Console.WriteLine($"Format Error: {ex.Message}");
        }
        catch(RecordNotFoundException ex){
            Console.WriteLine($"Record Error: {ex.Message}");
        }
        catch(Exception ex){
            Console.WriteLine($"General Error: {ex.Message}");
        }

        finally {
            Console.WriteLine("Finally block runs regardless of exceptions.");
        }
        
        
        Console.WriteLine("Execution completed.");
       
        
*/
/*
  try
        {
            int num = int.Parse("NotANumber");
        }
        catch (FormatException ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
        finally
        {
            Console.WriteLine("Execution completed.");
        }
*/